name: Build and publish Android app to Telegram

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build mobile client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Load secret files
        run: echo "$SIGNING_PROPERTIES_PROD" > ./mobile/signing.properties.prod
        shell: bash
        env:
          SIGNING_PROPERTIES_PROD: ${{ secrets.SIGNING_PROPERTIES_PROD }}

      - name: Build app
        run: ./gradlew assemble

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: src/mobile/build/outputs/apk/debug/

  test:
    name: Test mobile client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Load secret files
        run: echo "$SIGNING_PROPERTIES_PROD" > ./mobile/signing.properties.prod
        shell: bash
        env:
          SIGNING_PROPERTIES_PROD: ${{ secrets.SIGNING_PROPERTIES_PROD }}

      - name: Build app
        run: ./gradlew testDebugUnitTest

  deploy:
    name: Deploy
    needs: [ build, test ]
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: apk
          path: .


      - name: Push to Telegram
        run: |
          export VERSION_CODE=$(cat output-metadata.json | jq '.elements[0].versionCode')
          export VERSION_NAME=$(cat output-metadata.json | jq '.elements[0].versionName')

          curl -X POST \
            --form-string chat_id=${{ secrets.DEPLOY_TELEGRAM_GROUP }} \
            --form-string caption="✅ New apk for Tupperdate $VERSION_NAME ($VERSION_CODE)" \
            -F document=@mobile-debug.apk \
            https://api.telegram.org/bot${{ secrets.DEPLOY_TELEGRAM_TOKEN }}/sendDocument
