name: Deploy Website to GitHub Pages
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: |
          cd website
          yarn install
      - run: |
          cd website
          yarn build
      - run: cp website/CNAME website/dist/CNAME
        if : github.repository == 'heig-PDG/mono'
      - run: |
          cd website/dist/
          git init .
          git config user.name "${{github.actor}}"
          git config user.email "${{github.actor}}@users.noreply.github.com"
          git add .
          git commit -m "Deployed 🚀"
          git remote add origin https://${{secrets.TOKEN_GITHUB}}@github.com/${{github.repository}}.git
          git checkout -b gh-pages
          git push -u origin gh-pages --force
