name: Build and Test web app

on: [ pull_request ]

jobs:
  test:
    name: Test web app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Load secret files
        run: |
          echo "keystore.file=pr.jks" >> ./mobile/signing.properties.prod
          echo "keystore.password=123456" >> ./mobile/signing.properties.prod
          echo "alias.name=pr" >> ./mobile/signing.properties.prod
          echo "alias.password=123456" >> ./mobile/signing.properties.prod

      - name: Install Firebase Tools and Emulators
        run: sudo npm install -g firebase-tools

      - name: Run tests
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_GOOGLE_SERVICE_ACCOUNT }}
          GOOGLE_DATABASE_NAME: ${{ secrets.FIREBASE_GOOGLE_DATABASE_NAME }}
          GOOGLE_BUCKET_NAME: ${{ secrets.FIREBASE_GOOGLE_BUCKET_NAME }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          which java
          sudo firebase emulators:exec --only firestore --project tupperdate-developement 'which java'

      - name: Print debug logs
        if: ${{ always() }}
        run: |
          java -version
          which java
          ls -la
          find . -type f -name "fire*-debug.log" | xargs cat

      - name: Upload tests report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: report
          path: src/web/build/reports/tests/test/
