name: Deploy Website to GitHub Pages
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: |
          cd website
          yarn install

      - name: Build website
        run: |
          cd website
          yarn build

      - name: Configure GitHub Pages
        run: cp website/CNAME website/dist/CNAME
        if : github.repository == 'heig-PDG/mono'

      - name: Build artifact
        uses: actions/upload-artifact@master
        with:
          name: website
          path: website/dist


  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: website
          path: website/dist

      - name: Deploy to GitHub Pages
        run: |
          cd website/dist/
          git init .
          git config user.name "${{github.actor}}"
          git config user.email "${{github.actor}}@users.noreply.github.com"
          git add .
          git commit -m "Deployed 🚀"
          git remote add origin https://${{secrets.TOKEN_GITHUB}}@github.com/${{github.repository}}.git
          git checkout -b gh-pages
          git push -u origin gh-pages --force
